### ISSUE TITLE
[EPIC] Write documentation about new features

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#1457]
Some of the features I (@Donnype) have been working on have not been added to the documentation yet:
- [x] https://github.com/minvws/nl-kat-coordination/issues/1471
- [x] https://github.com/minvws/nl-kat-coordination/issues/1473
- [x] https://github.com/minvws/nl-kat-coordination/issues/1472
- [x] https://github.com/minvws/nl-kat-coordination/issues/1470
