### ISSUE TITLE
[OpenKAT v1.7] [Epic] Makefiles cleanup

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#146]
- [x] https://github.com/minvws/nl-rt-tim-abang/issues/833
- [x] https://github.com/minvws/nl-kat-coordination/issues/129
- [x] Rocky: be consistent in make commands (call Docker from Make)
