### ISSUE TITLE
Implement utils PyPy package for use in (containerized) boefjes

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#1468]
**Is your feature request related to a problem? Please describe.**
See https://github.com/minvws/nl-kat-coordination/issues/1198/, https://github.com/minvws/nl-kat-coordination/issues/1191, https://github.com/minvws/nl-kat-coordination/issues/1343, and https://github.com/minvws/nl-kat-coordination/issues/1373 for additional context on why a shared boefje utils package would be useful.

**Describe the solution you'd like**
After consulting with @ammar92 and @underdarknl, we have opted for the route where we (automatically) publish an installable pip package for use in (containerized) boefjes. In principle, future containerized boefjes can be in any arbitrary language, and we should be prepared for the possibility of having more helper packages in the tree.

**Describe alternatives you've considered**
When taking isolated, containerized boefjes in consideration, there is no clear-cut, easy way to expose/provide helper tooling. There was some discussion about whether we should supply extra tooling at all, given the increased maintenance burden for the team. The most important conclusion was that we should consider boefje input/output protocols to be authoritative, and this tooling is just a reference implementation of it.

**Subtasks**
- [ ] A proper place in the project tree for namespaced installable extra/optional packages
- [ ] GitHub Actions pipeline for automatically publishing a package to PyPy
- [ ] An important consideration is that any utils package must be lightweight and low-maintenance

**Comment by Darwinkel** [comment]
Blocked until the design for containerized boefjes are ready.

**Comment by brennodewinter** [comment]
Backlog consolidation: #1343 is being consolidated into this issue. This issue is the selected implementation direction for the shared Boefje utilities requested there: a lightweight, namespaced, installable package with an automated publishing pipeline and the I/O protocol remaining authoritative.
