### ISSUE TITLE
Enhance Task list search

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1587]
**Is your feature request related to a problem? Please describe.**
Currently one has to know the exact object name to search on

**Describe the solution you'd like**
- [ ] Allow search on characteristics (e.g. `example.com` instead of `Website|internet|<<IP>>|tcp|80|http|internet|example.com`
- [ ] Allow regex search
- [ ] Allow search through all columns (optionally using a query syntax, e.g. `boefje: masscan`

**Comment by underdarknl** [comment]
@jpbruinsslot can you make an inventory on what options we have for this? Jobs are in a postgresDB, so adding 'partial-text' queries should be doable within the SQL I'd say?

**Comment by jpbruinsslot** [comment]
Work has been done on the scheduler to support these kind of queries by extending the api with new filtering options (https://github.com/minvws/nl-kat-coordination/issues/1699)

**Comment by underdarknl** [comment]
Since these API's are not available, we should implement them into the scheduler client, and have them available to the user in the frontend.

**Comment by jpbruinsslot** [comment]
Can I help to elaborate on the supported functionality and filtering options in the scheduler api that would make this possible on the frontend?
