### ISSUE TITLE
[EPIC] Basic Security aggregate report

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#2081]
#### Overview table

![image](https://github.com/minvws/nl-kat-coordination/assets/46660228/93325dfc-abfa-435e-a270-827e32029205)

### Checks voor basic security.

Kan aanvulling gebruiken.

Doorgestreept (nog) niet mogelijk.

### DNS

- [ ] ~~Geen DNS zone transfers mogelijk    (niet mogelijk is goed)~~
- [ ] ~~Geen Cache poisoning mogelijk       (niet mogelijk is goed)~~
- [ ] ~~Beschikt over meest recente software versie~~
- [x] Geen onnodige poorten open
  - ~Everything except 53 UDP?~
  - Check for Uncommon port finding
- [x] DNSSEC aanwezig
  - No `Hostname.<ooi[is Finding].finding_type` with id "KAT-NO-DNSSEC"
- [x] Valide DNSSEC chain
  - The one above and no `Hostname.<ooi[is Finding].finding_type` with id "KAT-INVALID-DNSSEC"

### Web

IMPORTANT: we should ignore the duplicate Findings on Hostname that come from the internetnl bit.

![image](https://github.com/minvws/nl-kat-coordination/assets/46660228/5d9e62b2-4c5e-47aa-aa73-e9c190006f74)

- [ ] ~~Beschikt over meest recente software versie~~
- [ ] ~~Geen gebruik van standaard wachtwoorden op login panels~~
- [x] CSP header aanwezig
  - ~No `Hostname.<hostname[is Finding].finding_type` with id "KAT-NO-CSP"~ -> Internetnl bit
  - No `Hostname.<hostname[as Website].website[as HTTPResource].<ooi[is Finding].finding_type`  with id "KAT-NO-CSP"
- [x] Veilige configuratie CSP header
  - ~The one above and no `Hostname.<hostname[is Finding].finding_type` with id "KAT-CSP-VULNERABILITIES"~ -> Internetnl bit
  - The one above and no `Hostname.<hostname[as Website].website[as HTTPResource].resource[as HTTPHeader].<ooi[is Finding].finding_type` with id "KAT-CSP-VULNERABILITIES"
- [x] Valide CSP header
  - This will at most result in a "KAT-CSP-VULNERABILITIES" with the current normalizer (so: see above)
- [ ] ~~Cookies bevatten de 'httpOnly' flag~~
- [x] Redirect van HTTP naar HTTPS
  - No `Hostname.<netloc[is HostnameHTTPURL].<ooi[is Finding].finding_type` with id  "KAT-NO-HTTPS-REDIRECT"
  - OR: no `HTTPResource` with a `WebURL` and scheme http that has a not-null `redirects_to` a `WebURL` with scheme https?
- [x] Website biedt HTTPS aan
  - No `Hostname.hostname[is Website].<ooi[is Finding].finding_type` with id "KAT-NO-CERTIFICATE"
- [x] Security.txt bestand is aanwezig
  - There exists a `Hostname.hostname[is Website].<website [is SecurityTXT]` object
- [ ] ~~Alle resources worden over veilige verbindingen geladen ('Resource Loading')~~
- [ ] ~~Administratieve panels zijn niet vanaf het internet te bereiken. ~~
- [x] Geen onnodige poorten open
  - ~Everything except 80/443?~
  - Check for Uncommon port finding
- [ ] ~~Geen CORS policy beschikbaar~~
- [ ] ~~Geen Same-origin policy beschikbaar~~
- [ ] ~~CORS policy is niet restrictief genoeg~~
- [ ] ~~Same-origin policy is niet restrictief genoeg~~
- [x] Cerfiticaten aanwezig
  - check of Website object has certificate field
- [x] Certificaten niet verouderd
  - No `Hostname.<hostname[is Website].certificate.<ooi[is Finding].finding_type` with id "KAT-CERTIFICATE-EXPIRED"
  - Perhaps: also when ""KAT-CERTIFICATE-EXPIRING-SOON"?
       
### Mail

![image](https://github.com/minvws/nl-kat-coordination/assets/46660228/cf272dd9-fd35-4cd9-a8d3-5c53136547e2)

- [ ] ~~Beschikt over meest recente software versie~~
- [x] SPF record beschikbaar
- [ ] Valide SPF record
- [x] DKIM record beschikbaar
- [ ] ~~Valide DKIM chain ~~
- [x] DMARC record beschikbaar 
- [ ] ~~Valide DMARC record~~
- [ ] ~~SPF record bevat een veilige configuratie~~
- [ ] ~~DKIM record bevat een veilige configuratie~~
- [ ] ~~DMARC record bevat een veilige configuratie ~~
- [ ] Geen onnodige poorten open

        
### Other

- [ ] Geen administratieve poorten bereikbaar vanaf het internet (zie comment hierboven)
- [ ] Geen onnodige poorten open

        
## Safe connections
- [ ] Alle openstaande poorten ondersteunen encryptie (dus geen telnet of ftp, maar ssh en sftp)
- [x] Geen onveilige ciphers op ipservice

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
- onboarding flow layout is different from before, see the screenshot below.

- IPv6 report seems OK

- RPKI  -> Seems to contain invalid data, however cant PR doesn't work yet.  https://github.com/minvws/nl-kat-coordination/pull/2150

- Maybe hide all OOIs that have no data in the reports, or otherwise give the user an option to toggle this data to show/not show.

- For each of the basic security checks (DNS/mail/web/other) it would be nice to see a list of IPs/hosts that belong to this category, just like for the Open Ports and IPv6 reports. Thus chapter 5.3 System Specific Web gives an overview of the checks, but it's unclear for which IPs/Hosts this is, thus it becomes difficult to verify if the data is correct. It also makes it easier for the user to interpret the data. 
 
- Open ports are not shown for IPv6 hosts as we don't have IPv6 support with scanning and docker yet. 

- When selecting the OOIs during report generation it's difficult to select all OOIs when there are multiple pages of OOI. It's unclear if the 'Select all OOIs' at the top will select all OOIs of all the other pages as well. My assumption would be it does not (and should not), but a way to select all OOIs would be nice. 

- Generating reports is slow, for ~120 hostnames/IPs it takes about 10 minutes for a report to be generated. 

### What doesn't work:
Nothing found per se. The items above are not blocking for the release of RC1 imo. This can be tweaked/fixed in the upcoming time. 

### Bug or feature?:
See point above.

**Comment by HeleenSG** [comment]
@stephanie0x00 Thanks for letting me know. I've fixed the width of the checkbox labels in https://github.com/minvws/nl-kat-coordination/pull/2112.

**Comment by underdarknl** [comment]
> @stephanie0x00 Thanks for letting me know. I've fixed the width of the checkbox labels in #2112.

The max-line width of regular content (<p>) is still at 40rem, is that something we want to keep? As many pages and blocks are now only spanning half the size of the screen and introduce extra scrolling.

**Comment by underdarknl** [comment]
Lets revisit this, and move the remaining features to new issues, or fix them.
The admin panels are something we can already do, however im not sure it needs to be part of this report iteself. Maybe it would be better on a software report, or website report.
