### ISSUE TITLE
Phase out the KATalogus Repository Model

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#2983]
As part of this issue: https://github.com/minvws/nl-kat-coordination/issues/2881, please read that one to get more context.

### TODO

- [x] Remove references in the API, models, and remove the client and fix the tests
- [x] Make the plugin_state_id x organisation_pk combination unique instead of having the repository_pk as well
- [x] Check during migration that every plugin_state refers to the LOCAL repository, else fail and refer to the docs
- [x] Create migration tests for this behavior, including downgrades (seed the LOCAL repo and set it as default)
- [ ] Write docs and think about handling other existing repo's. Perhaps just remove those plugin_states.
