### ISSUE TITLE
Introduce the `Boefje` and `Normalizer` models in the KATalogus

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#2997]
Part of this epic: https://github.com/minvws/nl-kat-coordination/issues/2881

### Todo
- [x] Introduce the database models and migrations
- [x] Add plugin repository for boefjes and normalizers
- [x] Add router endpoints: post, get, patch, delete
- [x] Merge plugins with the local plugins in the PluginsService 
- [x] Expose to the API which plugins can be "deleted", since the local directories cannot
- [x] Handle id conflicts: override a set of fields that make sense to edit
