### ISSUE TITLE
Migrate the Setting model to a BoefjeConfig model and Introduce a NormalizerConfig model

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#3014]
Part of this epic: https://github.com/minvws/nl-kat-coordination/issues/2881

### Todo 
Migrate the Setting model to a BoefjeConfig model and Introduce a NormalizerConfig model:
- [x] Create the `boefje_config` table
- [x] Migrate all plugin_ids from settings to a plugin in the database using the local repository
- [x] Crash if we encounter a non-existing plugin_id (?)
- [x] Migrate all settings to a boefje_config entry
- [x] Drop the settings table
- [x] Add the `normalizer_config` table
- [x] Rename Settings to BoefjeConfig

And also migrate the `PluginState` model:
- [x] Remove the `PluginState` model, migrating the `enabled` field to the `Config` models, i.e. for each plugin_state:
- [x] Again add the local plugin to the database as a Boefje or Normalizer if it doesn't exist, based on the spec
  - [x] If based on `plugin_id` and `organisation_id` the `BoefjeConfig` exists, set enabled = plugin_state.enabled
  - [x] If it doesn't exists, create a BoefjeConfig or NormalizerConfig with enabled = plugin_state.enabled
