### ISSUE TITLE
EPIC: BITS & Policies

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3841]
In the UX workshop on openKAT dag 18th of October 2024 we've gathered insights into the uses of BITS & policies in the future of openKAT and are ready to start designing. This ticket will function as an epic, containing different sub tickets:

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 
- [ ] 4. Show applied policy in reports (part of all organisations flows #3761 but also within organisations).
- [ ] 5. Add/manage BITS/policies across multiple organisations. A central spot to view policies across organisations. (part of all organisations flows #3761)
- [ ] 6. Import policies from a URL into openKAT on organisation & all organisations level. (part of all organisations flows #3761 but also within organisations)
