### ISSUE TITLE
Create a boefje worker that can target specific tasks its image has been built for

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#3861]
Subticket of #3593 

## TODOs from https://github.com/minvws/nl-kat-coordination/issues/3698:
Since I needed those changes to test the rewrite, I merged this issue/work into this issue.

- [x] Create a generic image and adapter that handles the `oci_arguments` being the path to the targeted module
- [x] Rewrite all non-docker local boefjes by making the `run()` method accept a dict and hence drop the `BoefjeMeta` type hint as well. Also we need to add the `requirements.txt` back in the boefje directory.
- [x] Drop the requirements that are not needed anymore from the boefjes `pyproject.toml`
- [x] ~Create migration for boefjes in the `boefje` table: changing the boefjes.json for static boefjes means the db is out of sync for entries for that boefje. We need to either keep these aligned or make sure we ignore the fields for static database entries.~ **-> we should ignore the database entries for the time being**
- [x] Add [a cache volume](https://github.com/minvws/nl-kat-coordination/issues/3698#issuecomment-2432010321) to the generic image

TODO:
- [x] Add task_id from scheduler to the Origin for the reports:

![Image](https://github.com/user-attachments/assets/b9a77dd3-be6e-4b15-8702-419424ddc315)

- [x] Refactor toward being able to swap the scheduler API as a task API backend
- [x] Refactor toward being able to swap the boefje API as a task storage backend
- [x] Isolate worker module to easily turn containerized boefjes into workers without having the whole boefje app available
- [x] Build the generic worker image, including an OCI_IMAGE flag
- ~[ ] Add queues filter to CLI~ Actually we only apply this to boefjes currently
- [x] Add OCI image filter for scheduler tasks to CLI 
- [x] Apply OCI image filter in API call scheduler
- [x] https://github.com/minvws/nl-kat-coordination/issues/4208
- [x] Add plugin id filter to CLI 
- ~[ ] Add docker flag~ Workers inside boefjes cannot use docker, and the main worker _must_ use docker. Instead, there should be a flag that points to either the docker handler or a new k8s handler.
- [x] Test global worker (seems to work, waiting on #4208)
- [x] Build specialized images with a worker version as well
- [x] Test boefje worker
- [x] Update boefje signatures
- [x] Have a way to find duplicated boefjes not by local boefje.id, e.g. by image
- [x] Ignore normalizer and redundant files during copying to image

Scenario matrix:

| Boefje type | Example plugin        | OCI target works | Worker target works        |
| --------------- | ----------- | ----------------|---------------------------------------------------------- |
| [No OCI](https://github.com/minvws/nl-kat-coordination/issues/3855)   | ssl-version  | No, TODO | No, TODO |
| Generic Image          | dns-records         | Yes |          Yes           |
| Specialized Image    |  nmap         | Yes |          Yes           |
| Copied boefje           |  nmap-test         | Yes |          Yes           |

Subsequently but not blocking probably:
- [ ] https://github.com/minvws/nl-kat-coordination/issues/3855

---

We should have a long running process (worker) that can efficiently handle tasks within the generic boefje container.

## Implementation/design

We have tooling available already to run a worker that polls the scheduler and hands tasks off to separate processes. We should aim to reuse this where possible, but this leads to the following todos and questions:

- The `WorkerManager` imports all kinds of implementations specific to the boefjes, database, and katalogus that are not needed. This makes reusing code in a boefje container harder, so we could explore ways to refactor this and reduce the dependencies.
- The handler gets plugin information from the database, this should not be possible from the container. We should be able to use the boefje api instead for OI
- The current handler still delegates to the docker runner if there is an `oci_image` defined. This should not be possible when we're already in that `oci_image`. 
- We could consider not using multiprocessing, but that would make the worker more susceptive to being killed by the OOM as we've seen before. However, in that scenario it would be perhaps easier to detect it because the whole worker will die.
- We should poll the scheduler only for a specific set of boefjes based on the current `oci_image`. However, the `oci_image` itself is not known in the scheduler. We could however dynamically create a list of boefje ids available locally, since a worker will only start local boefjes. Moreover, we only need to do this on startup since the image needs to be rebuild and restarted if there are any changes in the list of available boefjes. In that case, we can start using the tasks endpoint in the scheduler and perform the following request (for the example of `dns-sec` and `dns-records`):
```bash
$ curl -X 'POST' \
  'http://localhost:8004/tasks?type=boefje&status=queued&offset=0&limit=10' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "filters": [
    {
      "column": "data",
      "field": "boefje__id",
      "operator": "in",
      "value": ["dns-sec", "dns-records"]
    }
  ]
}'
```
- It would be nice to make this all available in a single startup script where you can define (perhaps through the env):
  - The type of queue you are polling (boefje/normalizer/report)
  - (Perhaps some of the settings we expose through the environment, such as the amount of workers, poll interval, etc.)
  - A specific set of boefje_ids to additionally filter on
  - A flag to parse a boefje directory for the available boefje ids (additive wrt the previous flag)
  - A flag indicating whether we can delegate boefjes to Docker
  - A flag indicating if the handler should talk to Octopoes and Bytes or the Boefjes API
- We could now finally add the image hash in the `runnable_hash` field

---
## Technical Design Suggestions

I've added a schematic of the current scenario to define my language/notation for the system.

### The current scenario

```bash
$ python -m boefjes boefje
```

```mermaid
graph LR
    subgraph BC["God Boefje Container"]
        W["Worker[LocalHandler, DockerHandler]"]
        W --> C1["DNS Code"]
    end

    subgraph D["Single Boefje Container"]
        OCI["OCI Adapter"]
        C2["Nmap Code"]
    end

    W -- starts --> D
    OCI -- data --> BA["Boefje API"]
    BA -- task --> OCI
    Scheduler -- task --> BA
    OCI --> C2
    BA -- data --> Bytes
    Scheduler -- task --> W
```
---

### Suggested scenario

My idea was to be able to rewrite the worker so you can configure:
- If it should run local boefjes or oci images, or both
- Which boefje ids or oci_image it should filter for in the scheduler

Per convention, we could make this worker talk to the boefje API only for security reasons. Although this would create an extra hop to ask for tasks, I think using the flexible configuration could be powerful and reduce the headache in setting the system up performantly. And as shown in the below use-case overview, it would support most use-cases I could come up with. Also, note that perhaps there is no way to remove the redundant hop unless we allow talking to the scheduler directly from the "unsafe" boefje container, because we always need to communicate with both the scheduler and boefje api.

#### "This specific boefje needs a worker polling for its tasks"

```bash
$ python -m boefjes worker --queue boefje --ids nmap-tcp  # by default, use a local handler
```

```mermaid
graph LR
    subgraph BC["Single Boefje Container"]
        W["Worker[LocalHandler]"] --> C1["Nmap Code"]
    end

    W -- data --> BA["Boefje API"]
    BA -- task --> W
    BA -- data --> Bytes
    Scheduler -- task --> BA
```

#### "This set of (generic) Boefjes needs a worker polling for its tasks"

```bash
$ python -m boefjes worker --queue boefje --image "ghcr.io/jminvws/openkat/generic-boefje:latest"
```

```mermaid
graph LR
    subgraph BC["Generic Boefje Container"]
        W["Worker[LocalHandler]"] --> G1["Nmap Code"]
        W --> G2["DNS Code"]
        W --> G3["..."]
    end

    W -- data --> BA["Boefje API"]
    BA -- task --> W
    Scheduler -- task --> BA
    BA -- data --> Byes
```

#### "I can talk to the control plane and want to dynamically start (new) boefje images"

```bash
$ python -m boefjes worker --queue boefje --oci
```

```mermaid
graph LR
    subgraph BC["Docker Boefje Container"]
        W["Worker[DockerHandler]"]
    end

    subgraph D["Single Boefje Container"]
        OCI["OCI Adapter"]
        C["Boefje Code"]
    end

    W --> OCI
    Scheduler -- task --> BA["Boefje API"]
    BA -- task --> W
    OCI --> C
    BA -- task --> OCI
    OCI -- data --> BA
    BA -- data --> Bytes
```

#### "Just give me one worker that can do everything, even start (new) images"

```bash
$ python -m boefjes worker --queue boefje --oci --local
```

```mermaid
graph LR
    subgraph BC["God Boefje Container"]
        W["Worker[LocalHandler, DockerHandler]"]
        W --> C["DNS Code"]
    end

    subgraph D["Single Boefje Container"]
        OCI["OCI Adapter"]
        C1["Nmap Code"]
    end

    W -- data --> BA["Boefje API"]
    W -- starts --> D

    OCI --> C1
    BA -- task --> OCI
    BA -- task --> W
    OCI -- data --> BA
    Scheduler -- task --> BA
    BA -- data --> Bytes
```

**Comment by dekkers** [comment]
>     * We could consider not using multiprocessing, but that would make the worker more susceptive to being killed by the OOM as we've seen before. However, in that scenario it would be perhaps easier to detect it because the whole worker will die.

I don't really know what you are referring to, because as far as I remember we always used multiprocessing since I joined the project and can't find any issues related to this. I think resource-wise most boefjes will be limited by I/O. If we are going to create a container that can run multiple boefjes concurrently, this means it will be more efficient to use asyncio or threads than to use separate processes. I'd expect multiple processes to hit OOM earlier because they would use more memory.

>     * We should poll the scheduler only for a specific set of boefjes based on the current `oci_image`. However, the `oci_image` itself is not known in the scheduler. We could however dynamically create a list of boefje ids available locally, since a worker will only start local boefjes. Moreover, we only need to do this on startup since the image needs to be rebuild and restarted if there are any changes in the list of available boefjes. In that case, we can start using the tasks endpoint in the scheduler and perform the following request (for the example of `dns-sec` and `dns-records`):

But the boefje ids are not known locally, because if you create a new boefje they will be whatever id that the boefje got assigned. As far as I can see the only way is to filter by image name. So I guess we somehow need to make this information available in the scheduler to filter on if that isn't the case yet.

For multiple boefjes that can use the same image, the exact boefje is determined by the image name and an argument that indicates which boefje should run.

I think we also need to give the image name as argument when starting the container, because I think a container doesn't normally know what its image is.

> #### "I can talk to the control plane and want to dynamically start (new) boefje images"

I think the worker/docker handler and boefje API can be part of the same process.  

> #### "Just give me one worker that can do everything, even start (new) images"

This makes it more complex and less secure, but I don't see the advantages of doing this. So I don't think we should mix running boefje and talking to the control plane.

**Comment by Donnype** [comment]
> > ```
> > * We could consider not using multiprocessing, but that would make the worker more susceptive to being killed by the OOM as we've seen before. However, in that scenario it would be perhaps easier to detect it because the whole worker will die.
> > ```
> 
> I don't really know what you are referring to, because as far as I remember we always used multiprocessing since I joined the project and can't find any issues related to this. I think resource-wise most boefjes will be limited by I/O. If we are going to create a container that can run multiple boefjes concurrently, this means it will be more efficient to use asyncio or threads than to use separate processes. I'd expect multiple processes to hit OOM earlier because they would use more memory.
> 

It was an issue at ZCERT when we were using a process pool to manage worker processes. If the worker processes were killed by the OOM, the parent process would hang and do nothing. (This was caused by the memory limits set on the container in the production environment.) That was also the reason to switch to a "custom" implementation of the worker pool if I recall correctly. If the code runs in the main process, perhaps using threads, the OOM would target the right process and the orchestrator could show an alert, perhaps restart a worker, etc. One thing to consider with asyncio, though often very efficient, is having to rewrite the boefjes.

> > ```
> > * We should poll the scheduler only for a specific set of boefjes based on the current `oci_image`. However, the `oci_image` itself is not known in the scheduler. We could however dynamically create a list of boefje ids available locally, since a worker will only start local boefjes. Moreover, we only need to do this on startup since the image needs to be rebuild and restarted if there are any changes in the list of available boefjes. In that case, we can start using the tasks endpoint in the scheduler and perform the following request (for the example of `dns-sec` and `dns-records`):
> > ```
> 
> But the boefje ids are not known locally, because if you create a new boefje they will be whatever id that the boefje got assigned. As far as I can see the only way is to filter by image name. So I guess we somehow need to make this information available in the scheduler to filter on if that isn't the case yet.

Yes this was also mentioned by @underdarknl and that would indeed not be sufficient, I'll remove it from the list.

> For multiple boefjes that can use the same image, the exact boefje is determined by the image name and an argument that indicates which boefje should run.
> 
> I think we also need to give the image name as argument when starting the container, because I think a container doesn't normally know what its image is.

Agreed, we could expose this in the env perhaps, and probably build-time makes the most sense.

> > #### "I can talk to the control plane and want to dynamically start (new) boefje images"
> 
> I think the docker handler and boefje API can be part of the same process.

Definitely possible, but I also have a gut feeling that serving APIs and starting a worker in the same container clashes a bit with best-practices. At least _only_ providing this option could become a hassle in production systems because the worker and API might have to have different log streams and/or scaling needs. But we should also avoid having too many services. On that note: should we perhaps merge the KATalogus and boefje API until the KATalogus moves? We could also merge the boefje and normalizer worker and let users decide how to split workers in production. That would require adding the docker handler in the KATalogus or allow this worker to do both docker and local boefjes/normalizers still (see point below).

> > #### "Just give me one worker that can do everything, even start (new) images"
> 
> This makes it more complex and less secure, but I don't see the advantages of doing this. So I don't think we should mix running boefje and talking to the control plane.

It's mostly a drop-in replacement for the current boefje container, and I also mainly see the development setup as a use-case. If we can configure the worker to do either, it's a rather trivial addition to be able to pass tasks to different handlers (like we do now) without messing up the design. But in practice, you indeed usually want the separation.

**Comment by Donnype** [comment]
@underdarknl If there is no additional input, I will work on a first version that incorporates (most of) the ideas here. The first step - that I already started - is to do a refactor of the worker logic anyways. I also think that the perhaps final discussion points in this thread are about which process should run where and allow access to certain functionality - things that should be easy to change if the other functionality has been incorporated cleanly.

**Comment by underdarknl** [comment]
@dekkers could you do a review on this so we can Merge this quickly?
