### ISSUE TITLE
As a KAT user I want to filter the tasks on the task list

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#399]
Backend ticket in which these filter options were implemented in the scheduler Mula: https://github.com/minvws/nl-rt-tim-abang-mula/issues/156

- [ ] I want to filter tasks by scan tool (boefje = plugin_id)
- [ ] I want to filter tasks by date (started on, ended on, started between x and y)
- [ ] i want to filter tasks by object id/name (not sure if we can use the human readable value) -> Text input search filed would be the nicest option

**Comment by jpbruinsslot** [comment]
Relevent scheduler issue: https://github.com/minvws/nl-kat-coordination/issues/198

**Comment by zcrt** [comment]
In addition: I would like to filter based on status (failed, running, completed, ...)
